"""002 - create term and link tables

Revision ID: 93b42e7c1cef
Revises: acc0619feb9a
Create Date: 2021-06-25 15:59:03.926498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b42e7c1cef'
down_revision = 'acc0619feb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.String(length=250), nullable=True),
    sa.Column('domain', sa.String(length=250), nullable=False),
    sa.Column('tld', sa.String(length=250), nullable=False),
    sa.Column('href', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term',
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assoc_term_link',
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assoc_term_link')
    op.drop_table('term')
    op.drop_table('link')
    # ### end Alembic commands ###
