---
version: "3.5"
services:
#  nginx:
#    build:
#      context: .
#      dockerfile: nginx/Dockerfile
#    container_name: nginx
#    ports:
#      - "80:80"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-app
    env_file:
      - "vars.env"
    ports:
      - "8080:8080"
    volumes:
      - "./frontend/app/:/code/app"
    entrypoint: "dockerize -wait tcp://db-frontend:5432 -timeout 60s"
    command: ["/bin/ash", "-c", "/entrypoint.sh"]

  db-frontend:
    image: postgres:11
    container_name: db-frontend
    hostname: db-frontend
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=wikiman
      - POSTGRES_PASSWORD=w1k123
      - POSTGRES_DB=wikifrontend

  sqs-consumer:
    build:
      context: .
      dockerfile: sqs-consumer/Dockerfile
    container_name: sqs-consumer
    env_file:
      - "vars.env"
    entrypoint: ["dockerize", "-wait", "tcp://aws-stack:4566", "-timeout", "300s"]
    command: ["/code/start.sh"]

  aws-stack:
    image: localstack/localstack:latest
    hostname: aws-stack
    container_name: aws-stack
    environment:
      - SERVICES=sqs,dynamodb,ses,kinesis,lambda
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - PORT_WEB_UI=9999
      - HOSTNAME_EXTERNAL=aws-stack
    ports:
      - "9999:9999"
      - "4566:4566"
    volumes:
      - "./aws/startup:/docker-entrypoint-initaws.d"
      - "./aws/dynamodb-json/wikis.json:/tmp/wikis.json"
      - "./aws/lambda-files/py-handler.zip:/tmp/lambda-files/py-handler.zip"
      - "./data:/tmp/localstack"
