---
version: "3.5"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-app
    env_file:
      - "vars.env"
    ports:
      - "8080:8080"
    volumes:
      - "./frontend/app/:/code/app"
    entrypoint: "dockerize -wait tcp://db-frontend:5432 -timeout 60s"
    command: ["/bin/ash", "-c", "/entrypoint.sh"]

  db-frontend:
    image: postgres:11
    container_name: db-frontend
    hostname: db-frontend
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=wikiman
      - POSTGRES_PASSWORD=w1k123
      - POSTGRES_DB=wikifrontend

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker
    env_file:
      - "vars.env"
    entrypoint: ["dockerize", "-wait", "tcp://aws-stack:4569", "-timeout", "300s"]
    command: ["/code/start.sh"]

  aws-stack:
    image: localstack/localstack:latest
    hostname: aws-stack
    container_name: aws-stack
    environment:
      - SERVICES=sqs:4576,dynamodb:4569,ses:4579
      - DEBUG=1
    ports:
      - "4579:4579"
      - "4576:4576"
      - "4569:4569"
      - "4564:4564"
      - "8055:8080"
    volumes:
      - "./init-aws/scripts:/docker-entrypoint-initaws.d"
      - "./init-aws/dynamodb/wikis.json:/tmp/wikis.json"
      - "./data:/tmp/localstack"
